<a href="https://colab.research.google.com/github/mdzubayereashraf/Ostad-AI-Engineering-Course-Assignments/blob/main/Assignment_No_9_(_Regression).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Part-1: Loading the Dataset

In [ ]:
import pandas as pd
import numpy as np

data_url = "https://raw.githubusercontent.com/jbrownlee/Datasets/master/housing.data"

columns = ['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX','PTRATIO', 'B', 'LSTAT', 'MEDV']

df = pd.read_csv( data_url, sep=r'\s+',names=columns)

In [ ]:
df.head()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33,36.2

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   CRIM     506 non-null    float64
 1   ZN       506 non-null    float64
 2   INDUS    506 non-null    float64
 3   CHAS     506 non-null    int64
 4   NOX      506 non-null    float64
 5   RM       506 non-null    float64
 6   AGE      506 non-null    float64
 7   DIS      506 non-null    float64
 8   RAD      506 non-null    int64
 9   TAX      506 non-null    float64
 10  PTRATIO  506 non-null    float64
 11  B        506 non-null    float64
 12  LSTAT    506 non-null    float64
 13  MEDV     506 non-null    float64
dtypes: float64(12), int64(2)
memory usage: 55.5 KB

# Part-2: Spliting the Dataset

In [ ]:
from sklearn.model_selection import train_test_split

X = df.drop('MEDV', axis=1)
y = df['MEDV']

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

print("Training data:", X_train.shape)
print("Testing data:", X_test.shape)

Training data: (404, 13)
Testing data: (102, 13)

# Part 3: Train Regression Models

In [ ]:
from sklearn.linear_model import LinearRegression, Ridge, Lasso

# Create models
linear_model = LinearRegression()
ridge_model = Ridge()
lasso_model = Lasso(max_iter=10000)

# Train models
linear_model.fit(X_train, y_train)
ridge_model.fit(X_train, y_train)
lasso_model.fit(X_train, y_train)

Lasso(max_iter=10000)

# Part 4: Evaluating the Models#

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

linear_pred = linear_model.predict(X_test)
ridge_pred = ridge_model.predict(X_test)
lasso_pred = lasso_model.predict(X_test)

#### Linear Regression

In [ ]:
linear_mse = mean_squared_error(y_test, linear_pred)
linear_rmse = np.sqrt(linear_mse)
linear_r2 = r2_score(y_test, linear_pred)
linear_mae = mean_absolute_error(y_test, linear_pred)


print("Linear Regression")
print("MSE :", linear_mse)
print("RMSE:", linear_rmse)
print("R²  :", linear_r2)
print("MAE :", linear_mae)

Linear Regression
MSE : 24.291119474973478
RMSE: 4.928602182665332
R²  : 0.6687594935356326
MAE : 3.189091965887837

#### Ridge Regression

In [ ]:
ridge_mse = mean_squared_error(y_test, ridge_pred)
ridge_rmse = np.sqrt(ridge_mse)
ridge_r2 = r2_score(y_test, ridge_pred)
ridge_mae = mean_absolute_error(y_test, ridge_pred)

print("Ridge Regression")
print("MSE :", ridge_mse)
print("RMSE:", ridge_rmse)
print("R²  :", ridge_r2)
print("MAE :", ridge_mae)

Ridge Regression
MSE : 24.477191227708644
RMSE: 4.94744289787246
R²  : 0.6662221670168523
MAE : 3.1329474278055343

#### Lasso Regression

In [ ]:

lasso_mse = mean_squared_error(y_test, lasso_pred)
lasso_rmse = np.sqrt(lasso_mse)
lasso_r2 = r2_score(y_test, lasso_pred)
lasso_mae = mean_absolute_error(y_test, lasso_pred)


print("Lasso Regression")
print("MSE :", lasso_mse)
print("RMSE:", lasso_rmse)
print("R²  :", lasso_r2)
print("MAE :", lasso_mae)

Lasso Regression
MSE : 24.409489761299707
RMSE: 4.940596093721861
R²  : 0.6671453631686304
MAE : 3.2535397673681614

# Part 5: Comparing Results

In [ ]:
results = pd.DataFrame({
    'Model': ["Linear Regression","Ridge Regression","Lasso Regression"],
    'MSE': [linear_mse,ridge_mse,lasso_mse],
    'RMSE': [linear_rmse,ridge_rmse,lasso_rmse],
    'R²': [linear_r2,ridge_r2,lasso_r2],
    'MAE': [linear_mae,ridge_mae,lasso_mae]
})

results

               Model        MSE      RMSE        R²       MAE
0  Linear Regression  24.291119  4.928602  0.668759  3.189092
1   Ridge Regression  24.477191  4.947443  0.666222  3.132947
2   Lasso Regression  24.409490  4.940596  0.667145  3.253540